### ISSUE TITLE
tailscale interface patch broken

### ISSUE THREAD

**Issue by Ramblurr** [jack-broadway/vyos-module-tailscale#4]
Headsup, upstream removed the `show_interfaces.py` file on March 30, 2023, so the patch can no longer apply 

https://github.com/vyos/vyos-1x/commit/33b804c2030f8bc47acb3499a155a0e2f1f2db0f

**Comment by kylechase** [comment]
This should be fixed by applying patch #5

**Comment by Ramblurr** [comment]
Awesome thanks!
